5 module
js-tasks-ru/jsbasic-20220113_estelhawke pull request #5
Opened 2022-02-06 13:51 UTC by LaNadia

2022-02-06 13:51 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2022-02-06 17:08 UTC, SinimaWath requested changes

2022-02-06 17:08 UTC, SinimaWath commented on 5-module/1-task/index.js
> +  buttonToHide.addEventListener('click', function(event) {
- Давай стрелочную функцию
- Если не используешь аргумент event, его не стоит обьявлять

2022-02-06 17:08 UTC, SinimaWath commented on 5-module/2-task/index.js
> +  buttonToClick.addEventListener("click", function(event) {
- Давай стрелочную функцию
- Если не используешь аргумент event, его не стоит обьявлять

2022-02-07 15:44 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2022-02-08 12:24 UTC, SinimaWath approved these changes
Все ок!

2022-02-08 12:24 UTC, merged